export const inputs = {
  sourceLink: document.getElementById("sourceLink"),
  status: document.getElementById("status"),
  reloadDataBtn: document.getElementById("reloadDataBtn"),
  layerFilter: document.getElementById("layerFilter"),

  presetSelect: document.getElementById("presetSelect"),
  applyPresetBtn: document.getElementById("applyPresetBtn"),

  basemapSelect: document.getElementById("basemapSelect"),

  showWater: document.getElementById("showWater"),
  showParks: document.getElementById("showParks"),
  showLanduse: document.getElementById("showLanduse"),
  showRoadsMajor: document.getElementById("showRoadsMajor"),
  showRoadsMinor: document.getElementById("showRoadsMinor"),
  showBuildings: document.getElementById("showBuildings"),
  showBoundaries: document.getElementById("showBoundaries"),
  showRoadLabels: document.getElementById("showRoadLabels"),
  showPlaceLabels: document.getElementById("showPlaceLabels"),
  showPoiLabels: document.getElementById("showPoiLabels"),
  showWaterLabels: document.getElementById("showWaterLabels"),

  bgColor: document.getElementById("bgColor"),
  waterColor: document.getElementById("waterColor"),
  waterOpacity: document.getElementById("waterOpacity"),
  parkColor: document.getElementById("parkColor"),
  parkOpacity: document.getElementById("parkOpacity"),
  landuseColor: document.getElementById("landuseColor"),
  landuseOpacity: document.getElementById("landuseOpacity"),
  roadMajorColor: document.getElementById("roadMajorColor"),
  roadMajorOpacity: document.getElementById("roadMajorOpacity"),
  roadMinorColor: document.getElementById("roadMinorColor"),
  roadMinorOpacity: document.getElementById("roadMinorOpacity"),
  buildingColor: document.getElementById("buildingColor"),
  buildingOpacity: document.getElementById("buildingOpacity"),
  boundaryColor: document.getElementById("boundaryColor"),
  boundaryOpacity: document.getElementById("boundaryOpacity"),

  mapBrightness: document.getElementById("mapBrightness"),
  mapContrast: document.getElementById("mapContrast"),
  mapSaturation: document.getElementById("mapSaturation"),
  mapGrayscale: document.getElementById("mapGrayscale"),
  mapHue: document.getElementById("mapHue"),
  resetGlobalFiltersBtn: document.getElementById("resetGlobalFiltersBtn"),

  baseLabelColor: document.getElementById("baseLabelColor"),
  baseLabelOpacity: document.getElementById("baseLabelOpacity"),
  baseLabelHaloColor: document.getElementById("baseLabelHaloColor"),
  baseLabelHaloWidth: document.getElementById("baseLabelHaloWidth"),
  baseLabelSizeScale: document.getElementById("baseLabelSizeScale"),
  baseLabelTransform: document.getElementById("baseLabelTransform"),

  markerColor: document.getElementById("markerColor"),
  markerStroke: document.getElementById("markerStroke"),
  markerRadius: document.getElementById("markerRadius"),
  markerOpacity: document.getElementById("markerOpacity"),
  strokeWeight: document.getElementById("strokeWeight"),
  haloColor: document.getElementById("haloColor"),
  haloSize: document.getElementById("haloSize"),
  haloOpacity: document.getElementById("haloOpacity"),
  shadowColor: document.getElementById("shadowColor"),
  shadowOpacity: document.getElementById("shadowOpacity"),
  shadowBlur: document.getElementById("shadowBlur"),
  shadowOffsetX: document.getElementById("shadowOffsetX"),
  shadowOffsetY: document.getElementById("shadowOffsetY"),
  jitterMeters: document.getElementById("jitterMeters"),

  showLabels: document.getElementById("showLabels"),
  labelMode: document.getElementById("labelMode"),
  labelTransform: document.getElementById("labelTransform"),
  labelColor: document.getElementById("labelColor"),
  labelSize: document.getElementById("labelSize"),
  labelHaloColor: document.getElementById("labelHaloColor"),
  labelHaloWidth: document.getElementById("labelHaloWidth"),
  labelLetterSpacing: document.getElementById("labelLetterSpacing"),
  labelOffsetY: document.getElementById("labelOffsetY"),

  tintColor: document.getElementById("tintColor"),
  tintOpacity: document.getElementById("tintOpacity"),
  vignetteOpacity: document.getElementById("vignetteOpacity"),
  grainOpacity: document.getElementById("grainOpacity"),
  frameColor: document.getElementById("frameColor"),
  frameWidth: document.getElementById("frameWidth"),
  frameRadius: document.getElementById("frameRadius"),
  frameShadow: document.getElementById("frameShadow"),

  showPoster: document.getElementById("showPoster"),
  posterTitle: document.getElementById("posterTitle"),
  posterSubtitle: document.getElementById("posterSubtitle"),
  posterPosition: document.getElementById("posterPosition"),
  posterColor: document.getElementById("posterColor"),
  posterSize: document.getElementById("posterSize"),
  posterSubtitleSize: document.getElementById("posterSubtitleSize"),
  posterBgColor: document.getElementById("posterBgColor"),
  posterBgOpacity: document.getElementById("posterBgOpacity"),
  posterPadding: document.getElementById("posterPadding"),

  canvasRatio: document.getElementById("canvasRatio"),
  canvasPadding: document.getElementById("canvasPadding"),
  fitPadding: document.getElementById("fitPadding"),
  pitchInput: document.getElementById("pitchInput"),
  bearingInput: document.getElementById("bearingInput"),
  centerLat: document.getElementById("centerLat"),
  centerLng: document.getElementById("centerLng"),
  zoomInput: document.getElementById("zoomInput"),
  applyViewBtn: document.getElementById("applyViewBtn"),
  fitBtn: document.getElementById("fitBtn"),
  resetCameraBtn: document.getElementById("resetCameraBtn"),
  togglePanelBtn: document.getElementById("togglePanelBtn"),

  appShell: document.getElementById("appShell"),
  mapWrap: document.getElementById("mapWrap"),
  mapFrame: document.getElementById("mapFrame"),

  posterOverlay: document.getElementById("posterOverlay"),
  posterTitleNode: document.getElementById("posterTitleNode"),
  posterSubtitleNode: document.getElementById("posterSubtitleNode"),

  loadingOverlay: document.getElementById("loadingOverlay"),
  loadingText: document.getElementById("loadingText")
};
